// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transfer.proto

#include "transfer.pb.h"
#include "transfer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace transfer {

static const char* Transfer_method_names[] = {
  "/transfer.Transfer/L_I_D",
};

std::unique_ptr< Transfer::Stub> Transfer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Transfer::Stub> stub(new Transfer::Stub(channel));
  return stub;
}

Transfer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_L_I_D_(Transfer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Transfer::Stub::L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::transfer::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::transfer::Stmt1, ::transfer::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_L_I_D_, context, request, response);
}

void Transfer::Stub::experimental_async::L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::transfer::Stmt1, ::transfer::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_L_I_D_, context, request, response, std::move(f));
}

void Transfer::Stub::experimental_async::L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_L_I_D_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::transfer::Reply>* Transfer::Stub::PrepareAsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::transfer::Reply, ::transfer::Stmt1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_L_I_D_, context, request);
}

::grpc::ClientAsyncResponseReader< ::transfer::Reply>* Transfer::Stub::AsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncL_I_DRaw(context, request, cq);
  result->StartCall();
  return result;
}

Transfer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Transfer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Transfer::Service, ::transfer::Stmt1, ::transfer::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Transfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::transfer::Stmt1* req,
             ::transfer::Reply* resp) {
               return service->L_I_D(ctx, req, resp);
             }, this)));
}

Transfer::Service::~Service() {
}

::grpc::Status Transfer::Service::L_I_D(::grpc::ServerContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace transfer

