// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transfer.proto
#ifndef GRPC_transfer_2eproto__INCLUDED
#define GRPC_transfer_2eproto__INCLUDED

#include "transfer.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace transfer {

class Transfer final {
 public:
  static constexpr char const* service_full_name() {
    return "transfer.Transfer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::transfer::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>> AsyncL_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>>(AsyncL_I_DRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>> PrepareAsyncL_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>>(PrepareAsyncL_I_DRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>* AsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::transfer::Reply>* PrepareAsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::transfer::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::transfer::Reply>> AsyncL_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::transfer::Reply>>(AsyncL_I_DRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::transfer::Reply>> PrepareAsyncL_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::transfer::Reply>>(PrepareAsyncL_I_DRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void L_I_D(::grpc::ClientContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::transfer::Reply>* AsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::transfer::Reply>* PrepareAsyncL_I_DRaw(::grpc::ClientContext* context, const ::transfer::Stmt1& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_L_I_D_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status L_I_D(::grpc::ServerContext* context, const ::transfer::Stmt1* request, ::transfer::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_L_I_D() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestL_I_D(::grpc::ServerContext* context, ::transfer::Stmt1* request, ::grpc::ServerAsyncResponseWriter< ::transfer::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_L_I_D<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_L_I_D() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::transfer::Stmt1, ::transfer::Reply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::transfer::Stmt1* request, ::transfer::Reply* response) { return this->L_I_D(context, request, response); }));}
    void SetMessageAllocatorFor_L_I_D(
        ::grpc::experimental::MessageAllocator< ::transfer::Stmt1, ::transfer::Reply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::transfer::Stmt1, ::transfer::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* L_I_D(
      ::grpc::CallbackServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* L_I_D(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_L_I_D<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_L_I_D<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_L_I_D() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_L_I_D() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestL_I_D(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_L_I_D() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->L_I_D(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* L_I_D(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* L_I_D(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_L_I_D : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_L_I_D() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::transfer::Stmt1, ::transfer::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::transfer::Stmt1, ::transfer::Reply>* streamer) {
                       return this->StreamedL_I_D(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_L_I_D() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status L_I_D(::grpc::ServerContext* /*context*/, const ::transfer::Stmt1* /*request*/, ::transfer::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedL_I_D(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::transfer::Stmt1,::transfer::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_L_I_D<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_L_I_D<Service > StreamedService;
};

}  // namespace transfer


#endif  // GRPC_transfer_2eproto__INCLUDED
