// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transfer_file.proto

#include "transfer_file.pb.h"
#include "transfer_file.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace transferfile {

static const char* TransferFile_method_names[] = {
  "/transferfile.TransferFile/Upload",
};

std::unique_ptr< TransferFile::Stub> TransferFile::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TransferFile::Stub> stub(new TransferFile::Stub(channel));
  return stub;
}

TransferFile::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Upload_(TransferFile_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::transferfile::Chunk>* TransferFile::Stub::UploadRaw(::grpc::ClientContext* context, ::transferfile::Reply* response) {
  return ::grpc::internal::ClientWriterFactory< ::transferfile::Chunk>::Create(channel_.get(), rpcmethod_Upload_, context, response);
}

void TransferFile::Stub::experimental_async::Upload(::grpc::ClientContext* context, ::transferfile::Reply* response, ::grpc::experimental::ClientWriteReactor< ::transferfile::Chunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::transferfile::Chunk>::Create(stub_->channel_.get(), stub_->rpcmethod_Upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::transferfile::Chunk>* TransferFile::Stub::AsyncUploadRaw(::grpc::ClientContext* context, ::transferfile::Reply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::transferfile::Chunk>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::transferfile::Chunk>* TransferFile::Stub::PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::transferfile::Reply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::transferfile::Chunk>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, false, nullptr);
}

TransferFile::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TransferFile_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< TransferFile::Service, ::transferfile::Chunk, ::transferfile::Reply>(
          [](TransferFile::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::transferfile::Chunk>* reader,
             ::transferfile::Reply* resp) {
               return service->Upload(ctx, reader, resp);
             }, this)));
}

TransferFile::Service::~Service() {
}

::grpc::Status TransferFile::Service::Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::transferfile::Chunk>* reader, ::transferfile::Reply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace transferfile

